In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('C:/Users/thucheiz/Desktop/Pandas Demo/data/survey_results_public.csv', index_col='Respondent')

In [3]:
df

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,Yes,NaN,13,Monthly,NaN,NaN,Germany,European Euro,EUR,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,50.0,36,27
2,I am a developer by profession,No,NaN,19,NaN,NaN,NaN,United Kingdom,Pound sterling,GBP,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,NaN,7,4
3,I code primarily as a hobby,Yes,NaN,15,NaN,NaN,NaN,Russian Federation,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,4,NaN
4,I am a developer by profession,Yes,25.0,18,NaN,NaN,NaN,Albania,Albanian lek,ALL,...,NaN,NaN,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat less welcome now than last year,40.0,7,4
5,"I used to be a developer by profession, but no...",Yes,31.0,16,NaN,NaN,NaN,United States,NaN,NaN,...,Easy,Too short,No,"Computer science, computer engineering, or sof...",Django;Ruby on Rails,Ruby on Rails,Just as welcome now as I felt last year,NaN,15,8
6,I am a developer by profession,No,NaN,14,NaN,NaN,NaN,Germany,European Euro,EUR,...,Neither easy nor difficult,Appropriate in length,NaN,NaN,React.js,NaN,NaN,NaN,6,4
7,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,United States dollar,USD,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,A lot more welcome now than last year,NaN,6,4
8,I am a developer by profession,Yes,36.0,12,Yearly,116000.0,116000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;React.js;Vue.js,Flask,Just as welcome now as I felt last year,39.0,17,13
9,I am a developer by profession,No,30.0,20,NaN,NaN,NaN,Tunisia,United States dollar,USD,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular.js,jQuery,Just as welcome now as I felt last year,50.0,6,4
10,I am a developer by profession,Yes,22.0,14,Yearly,25000.0,32315.0,United Kingdom,Pound sterling,GBP,...,Easy,Appropriate in length,No,Mathematics or statistics,Flask;jQuery,Flask;jQuery,Somewhat more welcome now than last year,36.0,8,4
11,I am a developer by profession,Yes,23.0,13,Yearly,31000.0,40070.0,United Kingdom,Pound sterling,GBP,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Django;React.js,Angular;Angular.js;Django;React.js,Just as welcome now as I felt last year,40.0,10,2
12,I am a developer by profession,No,49.0,42,Monthly,1100.0,14268.0,Spain,European Euro,EUR,...,Easy,Appropriate in length,No,Mathematics or statistics,ASP.NET;jQuery,ASP.NET;jQuery,Just as welcome now as I felt last year,40.0,7,7
13,"I am not primarily a developer, but I write co...",Yes,53.0,14,Monthly,3000.0,38916.0,Netherlands,European Euro,EUR,...,Neither easy nor difficult,Too long,No,NaN,NaN,NaN,A lot less welcome now than last year,36.0,35,20
14,I am a developer by profession,Yes,27.0,13,Yearly,66000.0,66000.0,United States,United States dollar,USD,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Vue.js,Angular;Vue.js,Just as welcome now as I felt last year,40.0,5,1
15,I am a student who is learning to code,Yes,NaN,13,NaN,NaN,NaN,France,NaN,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,NaN,4,NaN
16,I am a developer by profession,Yes,45.0,8,Monthly,7000.0,108576.0,United Kingdom,Pound sterling,GBP,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,jQuery;React.js,Just as welcome now as I felt last year,50.0,37,23
17,I am a developer by profession,Yes,25.0,14,Yearly,79000.0,79000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core;Gatsby;React.js;Vue.js,ASP.NET;Gatsby;jQuery;React.js;Vue.js,Just as welcome now as I felt last year,40.0,7,3
18,I am a developer by profession,Yes,32.0,12,Monthly,105000.0,1260000.0,United States,United States dollar,USD,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,45.0,19,12
19,I am a developer by profession,No,24.0,15,Yearly,83400.0,83400.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;Express;React.js,Angular;Angular.js;ASP.NET Core,Just as welcome now as I felt last year,35.0,9,3
20,I am a developer by profession,Yes,40.0,18,NaN,NaN,NaN,Spain,European Euro,EUR,...,Easy,Too short,No,"Another engineering discipline (such as civil,...",Spring,Angular.js;Spring,Just as welcome now as I felt last year,50.0,22,17
21,I am a student who is learning to code,Yes,23.0,16,NaN,NaN,NaN,Belgium,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,NaN,Gatsby;React.js;Spring;Vue.js,Angular;ASP.NET Core;Express;React.js;Spring,NaN,NaN,7,NaN
22,I am a developer by profession,Yes,NaN,18,Monthly,NaN,NaN,India,Indian rupee,INR,...,Easy,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,50.0,10,2
23,I am a developer by profession,Yes,27.0,14,NaN,NaN,NaN,Germany,European Euro,EUR,...,Easy,Appropriate in length,No,"Another engineering discipline (such as civil,...",NaN,NaN,Somewhat less welcome now than last year,40.0,8,3
24,I am a developer by profession,Yes,45.0,14,Yearly,85000.0,91883.0,Germany,European Euro,EUR,...,Easy,Appropriate in length,No,"Another engineering discipline (such as civil,...",NaN,NaN,Just as welcome now as I felt last year,42.0,30,20
25,I am a developer by profession,No,NaN,25,Monthly,NaN,NaN,Portugal,European Euro,EUR,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,40.0,23,18
26,I am a developer by profession,No,NaN,12,Yearly,94000.0,71093.0,Canada,Canadian dollar,CAD,...,Easy,Too long,No,"Computer science, computer engineering, or sof...",NaN,Django;React.js,Just as welcome now as I felt last year,40.0,17,10
27,"I used to be a developer by profession, but no...",Yes,NaN,12,NaN,NaN,NaN,United States,NaN,NaN,...,Easy,Appropriate in length,No,"A humanities discipline (such as literature, h...",Flask,Flask,Just as welcome now as I felt last year,NaN,20,20
28,I am a student who is learning to code,Yes,NaN,22,NaN,NaN,NaN,China,NaN,NaN,...,Neither easy nor difficult,Too long,No,"A health science (such as nursing, pharmacy, r...",NaN,NaN,Just as welcome now as I felt last year,NaN,2,NaN
29,I am a student who is learning to code,Yes,18.0,15,NaN,NaN,NaN,Ukraine,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,NaN,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery...,NaN,Not applicable - I did not use Stack Overflow ...,NaN,Less than 1 year,NaN
30,I am a developer by profession,Yes,NaN,14,Yearly,30000.0,38778.0,United Kingdom,Pound sterling,GBP,...,Neither easy nor difficult,Too long,No,"Information systems, information technology, o...",Express;React.js;Vue.js,Express;Vue.js,A lot less welcome now than last year,37.0,4,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61121,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61490,NaN,Yes,NaN,14,NaN,NaN,NaN,United Kingdom,NaN,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Angular.js;Ruby on Rails,Flask;jQuery;Vue.js,Just as welcome now as I felt last year,NaN,13,NaN
61561,NaN,Yes,64.0,18,NaN,NaN,NaN,France,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,"Information systems, information technology, o...",Angular.js;jQuery;React.js;Vue.js,jQuery,A lot more welcome now than last year,NaN,30,NaN
61570,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61907,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Malaysia,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61918,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61983,NaN,Yes,NaN,25,NaN,NaN,NaN,Pakistan,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,No,NaN,Django;Flask,NaN,NaN,NaN,Less than 1 year,3
62391,NaN,Yes,NaN,Younger than 5 years,NaN,NaN,NaN,Morocco,NaN,NaN,...,Neither easy nor difficult,Too short,NaN,NaN,Angular.js;Express;React.js;Ruby on Rails,Angular.js;Express;React.js;Ruby on Rails,NaN,NaN,Less than 1 year,Less than 1 year
62464,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,...,NaN,NaN,NaN,I never declared a major,NaN,NaN,NaN,NaN,NaN,NaN
62605,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62834,NaN,Yes,17.0,10,NaN,NaN,NaN,Canada,NaN,NaN,...,Easy,Appropriate in length,No,NaN,NaN,NaN,Somewhat more welcome now than last year,NaN,7,NaN
62954,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,ASP.NET;ASP.NET Core;Django;jQuery;Symfony;Vue.js,NaN,NaN,NaN,NaN
63077,NaN,Yes,NaN,20,NaN,NaN,NaN,United States,NaN,NaN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,4,NaN
63396,NaN,Yes,NaN,24,NaN,NaN,NaN,Monaco,NaN,NaN,...,NaN,NaN,NaN,NaN,Gatsby,Gatsby,NaN,NaN,1,NaN
63452,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Russian Federation,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63640,NaN,Yes,NaN,8,NaN,NaN,NaN,Australia,NaN,NaN,...,NaN,NaN,No,NaN,Angular;Angular.js;Express;jQuery;React.js;Vue.js,Express;jQuery,Somewhat more welcome now than last year,NaN,6,2
63796,NaN,Yes,NaN,16,NaN,NaN,NaN,Bangladesh,NaN,NaN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,NaN,6,3
63820,NaN,Yes,NaN,17,NaN,NaN,NaN,Nepal,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,A lot less welcome now than last year,NaN,3,NaN
63994,NaN,Yes,NaN,27,NaN,NaN,NaN,Saudi Arabia,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,A lot more welcome now than last year,NaN,Less than 1 year,Less than 1 year
64013,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Bulgaria,NaN,NaN,...,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,Just as welcome now as I felt last year,NaN,NaN,NaN
64104,NaN,Yes,NaN,19,NaN,NaN,NaN,Poland,NaN,NaN,...,NaN,NaN,NaN,"Another engineering discipline (such as civil,...",NaN,NaN,NaN,NaN,2,NaN
64236,NaN,Yes,NaN,NaN,NaN,NaN,NaN,India,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64330,NaN,Yes,NaN,5,NaN,NaN,NaN,Thailand,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN
64480,NaN,Yes,NaN,21,NaN,NaN,NaN,Morocco,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Just as welcome now as I felt last year,NaN,3,NaN
64567,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Netherlands,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,ASP.NET Core,NaN,NaN,NaN,NaN
64858,NaN,Yes,NaN,16,NaN,NaN,NaN,United States,NaN,NaN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,10,Less than 1 year
64867,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Morocco,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64898,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Viet Nam,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
64925,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Poland,NaN,NaN,...,NaN,NaN,NaN,NaN,Angular;Angular.js;React.js,NaN,NaN,NaN,NaN,NaN
65112,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Spain,NaN,NaN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",ASP.NET Core;jQuery,Angular;Angular.js;ASP.NET Core;jQuery,NaN,NaN,NaN,NaN

In [4]:
schema_df = pd.read_csv('C:/Users/thucheiz/Desktop/Pandas Demo/data/survey_results_schema.csv')

In [5]:
schema_df

,Column,QuestionText
0,Respondent,Randomized respondent ID number (not in order ...
1,MainBranch,Which of the following options best describes ...
2,Hobbyist,Do you code as a hobby?
3,Age,What is your age (in years)? If you prefer not...
4,Age1stCode,At what age did you write your first line of c...
5,CompFreq,"Is that compensation weekly, monthly, or yearly?"
6,CompTotal,What is your current total compensation (salar...
7,ConvertedComp,Salary converted to annual USD salaries using ...
8,Country,Where do you live?
9,CurrencyDesc,Which currency do you use day-to-day? If your ...
10,CurrencySymbol,Which currency do you use day-to-day? If your ...
11,DatabaseDesireNextYear,Which database environments have you done exte...
12,DatabaseWorkedWith,Which database environments have you done exte...
13,DevType,Which of the following describe you? Please se...
14,EdLevel,Which of the following best describes the high...
15,Employment,Which of the following best describes your cur...
16,Ethnicity,"Which of the following describe you, if any? P..."
17,Gender,"Which of the following describe you, if any? P..."
18,JobFactors,Imagine that you are deciding between two job ...
19,JobSat,How satisfied are you with your current job? (...
20,JobSeek,Which of the following best describes your cur...
21,LanguageDesireNextYear,"Which programming, scripting, and markup langu..."
22,LanguageWorkedWith,"Which programming, scripting, and markup langu..."
23,MiscTechDesireNextYear,"Which other frameworks, libraries, and tools h..."
24,MiscTechWorkedWith,"Which other frameworks, libraries, and tools h..."
25,NEWCollabToolsDesireNextYear,Which collaboration tools have you done extens...
26,NEWCollabToolsWorkedWith,Which collaboration tools have you done extens...
27,NEWDevOps,Does your company have a dedicated DevOps person?
28,NEWDevOpsImpt,How important is the practice of DevOps to sca...
29,NEWEdImpt,"How important is a formal education, such as a..."
...,...,...
31,NEWJobHuntResearch,"When job searching, how do you learn more abou..."
32,NEWLearn,How frequently do you learn a new language or ...
33,NEWOffTopic,Do you think Stack Overflow should relax restr...
34,NEWOnboardGood,Do you think your company has a good onboardin...
35,NEWOtherComms,Are you a member of any other online developer...
36,NEWOvertime,How often do you work overtime or beyond the f...
37,NEWPurchaseResearch,"When buying a new tool or software, how do you..."
38,NEWPurpleLink,You search for a coding solution online and th...
39,NEWSOSites,Which of the following Stack Overflow sites ha...
40,NEWStuck,What do you do when you get stuck on a problem...
41,OpSys,What is the primary operating system in which ...
42,OrgSize,Approximately how many people are employed by ...
43,PlatformDesireNextYear,Which platforms have you done extensive develo...
44,PlatformWorkedWith,Which platforms have you done extensive develo...
45,PurchaseWhat,"What level of influence do you, personally, ha..."
46,Sexuality,"Which of the following describe you, if any? P..."
47,SOAccount,Do you have a Stack Overflow account?
48,SOComm,Do you consider yourself a member of the Stack...
49,SOPartFreq,How frequently would you say you participate i...
50,SOVisitFreq,How frequently would you say you visit Stack O...
51,SurveyEase,How easy or difficult was this survey to compl...
52,SurveyLength,How do you feel about the length of the survey...
53,Trans,Are you transgender?
54,UndergradMajor,What was your primary field of study?
55,WebframeDesireNextYear,Which web frameworks have you done extensive d...
56,WebframeWorkedWith,Which web frameworks have you done extensive d...
57,WelcomeChange,"Compared to last year, how welcome do you feel..."
58,WorkWeekHrs,"On average, how many hours per week do you wor..."
59,YearsCode,"Including any education, how many years have y..."
60,YearsCodePro,"NOT including education, how many years have y..."

In [6]:
schema_df.sort_values(by='Column')

,Column,QuestionText
3,Age,What is your age (in years)? If you prefer not...
4,Age1stCode,At what age did you write your first line of c...
5,CompFreq,"Is that compensation weekly, monthly, or yearly?"
6,CompTotal,What is your current total compensation (salar...
7,ConvertedComp,Salary converted to annual USD salaries using ...
8,Country,Where do you live?
9,CurrencyDesc,Which currency do you use day-to-day? If your ...
10,CurrencySymbol,Which currency do you use day-to-day? If your ...
11,DatabaseDesireNextYear,Which database environments have you done exte...
12,DatabaseWorkedWith,Which database environments have you done exte...
13,DevType,Which of the following describe you? Please se...
14,EdLevel,Which of the following best describes the high...
15,Employment,Which of the following best describes your cur...
16,Ethnicity,"Which of the following describe you, if any? P..."
17,Gender,"Which of the following describe you, if any? P..."
2,Hobbyist,Do you code as a hobby?
18,JobFactors,Imagine that you are deciding between two job ...
19,JobSat,How satisfied are you with your current job? (...
20,JobSeek,Which of the following best describes your cur...
21,LanguageDesireNextYear,"Which programming, scripting, and markup langu..."
22,LanguageWorkedWith,"Which programming, scripting, and markup langu..."
1,MainBranch,Which of the following options best describes ...
23,MiscTechDesireNextYear,"Which other frameworks, libraries, and tools h..."
24,MiscTechWorkedWith,"Which other frameworks, libraries, and tools h..."
25,NEWCollabToolsDesireNextYear,Which collaboration tools have you done extens...
26,NEWCollabToolsWorkedWith,Which collaboration tools have you done extens...
27,NEWDevOps,Does your company have a dedicated DevOps person?
28,NEWDevOpsImpt,How important is the practice of DevOps to sca...
29,NEWEdImpt,"How important is a formal education, such as a..."
30,NEWJobHunt,"In general, what drives you to look for a new ..."
...,...,...
32,NEWLearn,How frequently do you learn a new language or ...
33,NEWOffTopic,Do you think Stack Overflow should relax restr...
34,NEWOnboardGood,Do you think your company has a good onboardin...
35,NEWOtherComms,Are you a member of any other online developer...
36,NEWOvertime,How often do you work overtime or beyond the f...
37,NEWPurchaseResearch,"When buying a new tool or software, how do you..."
38,NEWPurpleLink,You search for a coding solution online and th...
39,NEWSOSites,Which of the following Stack Overflow sites ha...
40,NEWStuck,What do you do when you get stuck on a problem...
41,OpSys,What is the primary operating system in which ...
42,OrgSize,Approximately how many people are employed by ...
43,PlatformDesireNextYear,Which platforms have you done extensive develo...
44,PlatformWorkedWith,Which platforms have you done extensive develo...
45,PurchaseWhat,"What level of influence do you, personally, ha..."
0,Respondent,Randomized respondent ID number (not in order ...
47,SOAccount,Do you have a Stack Overflow account?
48,SOComm,Do you consider yourself a member of the Stack...
49,SOPartFreq,How frequently would you say you participate i...
50,SOVisitFreq,How frequently would you say you visit Stack O...
46,Sexuality,"Which of the following describe you, if any? P..."
51,SurveyEase,How easy or difficult was this survey to compl...
52,SurveyLength,How do you feel about the length of the survey...
53,Trans,Are you transgender?
54,UndergradMajor,What was your primary field of study?
55,WebframeDesireNextYear,Which web frameworks have you done extensive d...
56,WebframeWorkedWith,Which web frameworks have you done extensive d...
57,WelcomeChange,"Compared to last year, how welcome do you feel..."
58,WorkWeekHrs,"On average, how many hours per week do you wor..."
59,YearsCode,"Including any education, how many years have y..."
60,YearsCodePro,"NOT including education, how many years have y..."

In [7]:
df.loc[1, 'Hobbyist']

'Yes'

In [8]:
high_salary = df['ConvertedComp'] > 900000

In [9]:
df.loc[high_salary,['Country', 'ConvertedComp']].head(20)

                   Country  ConvertedComp
Respondent
18           United States      1260000.0
57           United States      1620000.0
65           United States      1176000.0
123          United States      2000000.0
125          United States      2000000.0
193          United States      2000000.0
196          United States      1920000.0
281          United States      1104000.0
313                 Canada      1000000.0
503          United States      1500000.0
665          United States      2000000.0
685         United Kingdom       958584.0
699          United States      2000000.0
724          United States      2000000.0
818          United States      2000000.0
839          United States      1260000.0
903         United Kingdom      1000000.0
935                 Canada      1000000.0
939         United Kingdom      1000000.0
954            Switzerland      1000000.0

In [10]:
countries = ['United States', 'Switzerland', 'United Kingdom', 'Canada', 'India']

In [11]:
filt = df['Country'].isin(countries)

In [12]:
df.loc[filt, 'Country']

Respondent
2        United Kingdom
5         United States
7                 India
8         United States
10       United Kingdom
11       United Kingdom
14        United States
16       United Kingdom
17        United States
18        United States
19        United States
22                India
26               Canada
27        United States
30       United Kingdom
32               Canada
35        United States
36       United Kingdom
39       United Kingdom
40        United States
41        United States
42        United States
43        United States
47       United Kingdom
48        United States
49        United States
51               Canada
52       United Kingdom
53        United States
54        United States
              ...
38854             India
42314     United States
42965             India
43211     United States
44176     United States
44880             India
45374     United States
45440     United States
45721     United States
49544     United States
51405             India
52184             India
52304     United States
53549     United States
53697     United States
54068     United States
54361     United States
54757             India
55407             India
58498     United States
58896     United States
59638    United Kingdom
60931     United States
61490    United Kingdom
62464             India
62834            Canada
62954             India
63077     United States
64236             India
64858     United States
Name: Country, Length: 27588, dtype: object

In [13]:
# Display all strings that contain python
filt = df['LanguageWorkedWith'].str.contains('Python', na=False)

In [14]:
df.loc[filt, 'LanguageWorkedWith'].head(10)

Respondent
3                             Objective-C;Python;Swift
8                                           Python;SQL
10                 HTML/CSS;Java;JavaScript;Python;SQL
13                                 C;JavaScript;Python
15    Bash/Shell/PowerShell;C;HTML/CSS;Java;Python;SQL
17               C#;HTML/CSS;JavaScript;Python;SQL;VBA
22                                         Java;Python
26                                   JavaScript;Python
27         Bash/Shell/PowerShell;C;C++;Java;Python;SQL
28                                            Python;R
Name: LanguageWorkedWith, dtype: object

In [16]:
df.sort_values(by='Country', inplace=True)

In [17]:
df

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
8631,I am a student who is learning to code,No,NaN,19,NaN,NaN,NaN,Afghanistan,NaN,NaN,...,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",Spring,Angular.js,Somewhat more welcome now than last year,NaN,3,NaN
25001,I am a developer by profession,No,NaN,Younger than 5 years,Weekly,NaN,NaN,Afghanistan,United Arab Emirates dirham,AED,...,Easy,Too short,Yes,NaN,NaN,Angular,A lot less welcome now than last year,NaN,Less than 1 year,Less than 1 year
58171,I am a student who is learning to code,Yes,23.0,18,NaN,NaN,NaN,Afghanistan,NaN,NaN,...,Easy,Appropriate in length,NaN,NaN,ASP.NET;Spring,Laravel;Spring,A lot more welcome now than last year,NaN,5,NaN
42668,I am a developer by profession,Yes,NaN,NaN,NaN,NaN,NaN,Afghanistan,Afghan afghani,AFN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51509,I am a developer by profession,No,28.0,19,Monthly,1.300000e+05,20220.0,Afghanistan,Afghan afghani,AFN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;Express,Angular,Just as welcome now as I felt last year,40.0,8,5
37951,I am a student who is learning to code,Yes,NaN,NaN,NaN,NaN,NaN,Afghanistan,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28374,I am a developer by profession,Yes,NaN,7,Yearly,1.300000e+05,130000.0,Afghanistan,United States dollar,USD,...,Neither easy nor difficult,Appropriate in length,No,Mathematics or statistics,NaN,NaN,Just as welcome now as I felt last year,NaN,17,5
7616,I am a developer by profession,No,24.0,20,NaN,NaN,NaN,Afghanistan,Afghan afghani,AFN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Angular;ASP.NET;Django;Vue.js,Angular;Drupal;Laravel;Vue.js,Somewhat less welcome now than last year,40.0,5,2
43966,I am a student who is learning to code,Yes,25.0,13,NaN,NaN,NaN,Afghanistan,NaN,NaN,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,NaN,9,NaN
62698,I am a developer by profession,Yes,NaN,Younger than 5 years,Weekly,NaN,NaN,Afghanistan,Thai baht,THB,...,Easy,Too long,No,NaN,Symfony,NaN,NaN,NaN,Less than 1 year,Less than 1 year
51532,I am a developer by profession,Yes,NaN,NaN,NaN,NaN,NaN,Afghanistan,Netherlands Antillean guilder,ANG,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36574,I am a developer by profession,No,NaN,NaN,NaN,NaN,NaN,Afghanistan,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43946,I am a student who is learning to code,Yes,NaN,NaN,NaN,NaN,NaN,Afghanistan,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Angular;Angular.js;ASP.NET;jQuery;Laravel;Reac...,NaN,NaN,NaN,NaN
65381,I am a developer by profession,No,NaN,8,Weekly,8.740000e+09,1000000.0,Afghanistan,Afghan afghani,AFN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,30,35
38672,I am a developer by profession,No,NaN,5,Monthly,1.225000e+06,231192.0,Afghanistan,Russian ruble,RUB,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40,40
35753,I am a developer by profession,Yes,NaN,18,Monthly,5.000000e+03,780.0,Afghanistan,Afghan afghani,AFN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,NaN,4,1
43808,I am a developer by profession,Yes,NaN,NaN,NaN,NaN,NaN,Afghanistan,United Arab Emirates dirham,AED,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37159,I am a student who is learning to code,Yes,NaN,NaN,NaN,NaN,NaN,Afghanistan,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44555,I am a developer by profession,No,NaN,20,NaN,NaN,NaN,Afghanistan,NaN,NaN,...,NaN,NaN,NaN,Web development or web design,NaN,NaN,NaN,NaN,5,3
35687,I am a student who is learning to code,No,NaN,NaN,NaN,NaN,NaN,Afghanistan,NaN,NaN,...,NaN,NaN,NaN,NaN,Angular;Angular.js;ASP.NET;ASP.NET Core;jQuery,Angular.js;ASP.NET,Somewhat less welcome now than last year,NaN,NaN,NaN
37605,NaN,Yes,NaN,NaN,NaN,NaN,NaN,Afghanistan,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44556,I am a developer by profession,No,NaN,17,NaN,NaN,NaN,Afghanistan,Afghan afghani,AFN,...,NaN,NaN,NaN,"Computer science, computer engineering, or sof...",NaN,NaN,NaN,NaN,12,3
23798,I am a developer by profession,Yes,NaN,Younger than 5 years,NaN,NaN,NaN,Afghanistan,NaN,NaN,...,NaN,Too long,NaN,NaN,NaN,Angular,NaN,NaN,1,NaN
42188,I am a student who is learning to code,Yes,NaN,9,NaN,NaN,NaN,Afghanistan,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN
65456,I am a developer by profession,Yes,NaN,Younger than 5 years,Weekly,5.521171e+09,1000000.0,Afghanistan,Afghan afghani,AFN,...,NaN,NaN,NaN,"Information systems, information technology, o...",NaN,NaN,NaN,NaN,More than 50 years,More than 50 years
44697,I am a developer by profession,Yes,NaN,NaN,NaN,NaN,NaN,Afghanistan,NaN,NaN,...,NaN,NaN,NaN,"Information systems, information technology, o...",NaN,NaN,NaN,NaN,NaN,NaN
60507,I am a student who is learning to code,Yes,NaN,18,NaN,NaN,NaN,Afghanistan,NaN,NaN,...,Neither easy nor difficult,Appropriate in length,NaN,"Computer science, computer engineering, or sof...",Laravel,Laravel,NaN,NaN,NaN,NaN
898,I am a developer by profession,Yes,NaN,NaN,Monthly,NaN,NaN,Afghanistan,Australian dollar,AUD,...,Neither easy nor difficult,Appropriate in length,No,"A natural science (such as biology, chemistry,...",NaN,NaN,NaN,NaN,4,3
51900,I am a student who is learning to code,Yes,NaN,NaN,NaN,NaN,NaN,Afghanistan,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35179,I am a developer by profession,Yes,NaN,NaN,NaN,NaN,NaN,Afghanistan,Afghan afghani,AFN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34827,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35643,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36113,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36448,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40550,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41922,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42026,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42825,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43177,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44670,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44891,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46810,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51650,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51958,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53347,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54379,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54654,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55156,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55162,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55314,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55417,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56415,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57583,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58915,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59962,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60055,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61121,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61570,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61918,NaN,Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62605,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
df[['Country', 'ConvertedComp']]

                Country  ConvertedComp
Respondent
8631        Afghanistan            NaN
25001       Afghanistan            NaN
58171       Afghanistan            NaN
42668       Afghanistan            NaN
51509       Afghanistan        20220.0
37951       Afghanistan            NaN
28374       Afghanistan       130000.0
7616        Afghanistan            NaN
43966       Afghanistan            NaN
62698       Afghanistan            NaN
51532       Afghanistan            NaN
36574       Afghanistan            NaN
43946       Afghanistan            NaN
65381       Afghanistan      1000000.0
38672       Afghanistan       231192.0
35753       Afghanistan          780.0
43808       Afghanistan            NaN
37159       Afghanistan            NaN
44555       Afghanistan            NaN
35687       Afghanistan            NaN
37605       Afghanistan            NaN
44556       Afghanistan            NaN
23798       Afghanistan            NaN
42188       Afghanistan            NaN
65456       Afghanistan      1000000.0
44697       Afghanistan            NaN
60507       Afghanistan            NaN
898         Afghanistan            NaN
51900       Afghanistan            NaN
35179       Afghanistan            NaN
...                 ...            ...
34827               NaN            NaN
35643               NaN            NaN
36113               NaN            NaN
36448               NaN            NaN
40550               NaN            NaN
41922               NaN            NaN
42026               NaN            NaN
42825               NaN            NaN
43177               NaN            NaN
44670               NaN            NaN
44891               NaN            NaN
46810               NaN            NaN
51650               NaN            NaN
51958               NaN            NaN
53347               NaN            NaN
54379               NaN            NaN
54654               NaN            NaN
55156               NaN            NaN
55162               NaN            NaN
55314               NaN            NaN
55417               NaN            NaN
56415               NaN            NaN
57583               NaN            NaN
58915               NaN            NaN
59962               NaN            NaN
60055               NaN            NaN
61121               NaN            NaN
61570               NaN            NaN
61918               NaN            NaN
62605               NaN            NaN

[64461 rows x 2 columns]

In [21]:
df['ConvertedComp'].nlargest(10)

Respondent
54263    2000000.0
5725     2000000.0
43430    2000000.0
59279    2000000.0
46711    2000000.0
1793     2000000.0
3072     2000000.0
3045     2000000.0
1413     2000000.0
3261     2000000.0
Name: ConvertedComp, dtype: float64

In [22]:
df.nlargest(10, 'ConvertedComp')

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
54263,I am a developer by profession,Yes,29.0,10,Weekly,7.000000e+04,2000000.0,Canada,United States dollar,USD,...,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",React.js;Vue.js,Express;Flask;jQuery,Just as welcome now as I felt last year,36.0,14,5
5725,I am a developer by profession,No,26.0,14,Monthly,1.800000e+05,2000000.0,Canada,United States dollar,USD,...,Easy,Too short,No,"Computer science, computer engineering, or sof...",Gatsby,Spring,Not applicable - I did not use Stack Overflow ...,40.0,10,4
43430,I am a developer by profession,Yes,33.0,17,Monthly,1.710000e+05,2000000.0,Italy,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,40.0,13,2
59279,I am a developer by profession,Yes,NaN,12,Monthly,3.000000e+05,2000000.0,Nepal,United States dollar,USD,...,Neither easy nor difficult,Too long,NaN,"Computer science, computer engineering, or sof...",Django;Drupal;Flask;Gatsby;Laravel,Angular;Angular.js;ASP.NET;ASP.NET Core;Expres...,A lot more welcome now than last year,40.0,20,14
46711,I am a developer by profession,Yes,NaN,Younger than 5 years,Yearly,1.000000e+56,2000000.0,Nomadic,United States dollar,USD,...,NaN,NaN,NaN,NaN,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,NaN,168.0,More than 50 years,More than 50 years
1793,I am a developer by profession,Yes,27.0,16,Weekly,1.200000e+05,2000000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Just as welcome now as I felt last year,40.0,12,NaN
3072,I am a developer by profession,Yes,32.0,22,Weekly,1.020000e+05,2000000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core;Flask,ASP.NET Core,Somewhat less welcome now than last year,40.0,10,7
3045,I am a developer by profession,Yes,35.0,12,Weekly,1.000000e+05,2000000.0,United States,United States dollar,USD,...,Neither easy nor difficult,Too long,No,"Computer science, computer engineering, or sof...",Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,Angular;Angular.js;ASP.NET;ASP.NET Core;Django...,Just as welcome now as I felt last year,42.0,23,5
1413,I am a developer by profession,Yes,25.0,12,Weekly,4.100000e+04,2000000.0,United States,United States dollar,USD,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",jQuery;Laravel,jQuery,Just as welcome now as I felt last year,37.0,13,3
3261,I am a developer by profession,Yes,34.0,23,Weekly,1.150000e+05,2000000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",Django;jQuery;Spring,Spring,Just as welcome now as I felt last year,60.0,11,9

In [23]:
df['ConvertedComp'].mean()

103756.05014961446

In [24]:
df['ConvertedComp'].median()

54049.0

In [25]:
df.describe()

                Age      CompTotal  ConvertedComp   WorkWeekHrs
count  45446.000000   3.482600e+04   3.475600e+04  41151.000000
mean      30.834111  3.190464e+242   1.037561e+05     40.782174
std        9.585392            inf   2.268853e+05     17.816383
min        1.000000   0.000000e+00   0.000000e+00      1.000000
25%       24.000000   2.000000e+04   2.464800e+04     40.000000
50%       29.000000   6.300000e+04   5.404900e+04     40.000000
75%       35.000000   1.250000e+05   9.500000e+04     44.000000
max      279.000000  1.111111e+247   2.000000e+06    475.000000

In [26]:
df['ConvertedComp'].count()

34756

In [31]:
df['Hobbyist'].count()

64416

In [32]:
df['Hobbyist'].value_counts()

Yes    50388
No     14028
Name: Hobbyist, dtype: int64

In [39]:
df['PlatformWorkedWith'].value_counts(normalize=True)

Windows                                                                                                                                 0.088591
Linux;Windows                                                                                                                           0.045707
Linux                                                                                                                                   0.039225
Android                                                                                                                                 0.022306
Microsoft Azure;Windows                                                                                                                 0.018498
Docker;Linux                                                                                                                            0.017124
Android;Windows                                                                                                                         0.014059
Docker;Linux;Windows                                                                                                                    0.012072
AWS;Docker;Linux                                                                                                                        0.009156
Android;Linux;Windows                                                                                                                   0.008878
Windows;WordPress                                                                                                                       0.008803
Android;iOS                                                                                                                             0.008748
WordPress                                                                                                                               0.008655
AWS                                                                                                                                     0.008636
Linux;MacOS                                                                                                                             0.007615
iOS                                                                                                                                     0.007540
Microsoft Azure                                                                                                                         0.007466
MacOS                                                                                                                                   0.007392
AWS;Linux                                                                                                                               0.007076
Linux;MacOS;Windows                                                                                                                     0.006668
Linux;Raspberry Pi;Windows                                                                                                              0.006315
Docker                                                                                                                                  0.006092
AWS;Docker                                                                                                                              0.005665
Linux;Windows;WordPress                                                                                                                 0.005627
AWS;Docker;Linux;MacOS                                                                                                                  0.005497
MacOS;Windows                                                                                                                           0.005330
Android;Linux                                                                                                                           0.005237
Docker;Windows                                                                                                                          0.005200
AWS;Linux;Windows                                                                                                                       0.005089
AWS;Docker;Linux;Windows                                                                                                                0.004643
                                                                                                                                          ...
AWS;Docker;Heroku;Kubernetes;MacOS;Windows;WordPress                                                                                    0.000019
AWS;Docker;Google Cloud Platform;MacOS;Windows;WordPress                                                                                0.000019
Android;AWS;Docker;Google Cloud Platform;iOS;Kubernetes;MacOS;Slack Apps and Integrations;WordPress                                     0.000019
Android;Arduino;AWS;Google Cloud Platform;Linux;Windows;WordPress                                                                       0.000019
Android;Arduino;AWS;Google Cloud Platform;Microsoft Azure;Windows                                                                       0.000019
Docker;Linux;MacOS;Microsoft Azure;Raspberry Pi;Windows;WordPress                                                                       0.000019
Android;Arduino;AWS;Docker;iOS;Linux;MacOS;WordPress                                                                                    0.000019
Android;AWS;Docker;Google Cloud Platform;Linux;MacOS;Raspberry Pi;Slack Apps and Integrations;Windows                                   0.000019
Android;AWS;Docker;Google Cloud Platform;IBM Cloud or Watson;iOS;Linux;Microsoft Azure;Slack Apps and Integrations;Windows;WordPress    0.000019
Android;Arduino;Google Cloud Platform;iOS;Linux;Microsoft Azure;Raspberry Pi;Windows                                                    0.000019
Docker;iOS;Linux;MacOS;Slack Apps and Integrations                                                                                      0.000019
Google Cloud Platform;Linux;Microsoft Azure;WordPress                                                                                   0.000019
Arduino;AWS;Docker;Google Cloud Platform;iOS;Linux;MacOS;Windows                                                                        0.000019
AWS;Docker;Heroku;IBM Cloud or Watson;Linux;Slack Apps and Integrations                                                                 0.000019
Android;Arduino;Google Cloud Platform;iOS;MacOS;Raspberry Pi                                                                            0.000019
AWS;Docker;Heroku;iOS;Linux;Windows                                                                                                     0.000019
Arduino;AWS;Heroku;Linux;MacOS;Raspberry Pi;Windows                                                                                     0.000019
Android;Arduino;AWS;Docker;Raspberry Pi                                                                                                 0.000019
Arduino;AWS;Docker;iOS;Kubernetes;Linux;Raspberry Pi;Windows;WordPress                                                                  0.000019
Android;Google Cloud Platform;iOS;Linux;MacOS;Microsoft Azure;Raspberry Pi;Windows;WordPress                                            0.000019
Android;Arduino;AWS;Docker;Heroku;Linux;MacOS;Microsoft Azure;Raspberry Pi                                                              0.000019
Android;AWS;Docker;Google Cloud Platform;Heroku;Kubernetes;MacOS;Windows                                                                0.000019
Arduino;Docker;Google Cloud Platform;Heroku;Kubernetes;Linux;Microsoft Azure;Raspberry Pi;Slack Apps and Integrations                   0.000019
AWS;Docker;Google Cloud Platform;Kubernetes;Microsoft Azure;Slack Apps and Integrations                                                 0.000019
iOS;Linux;MacOS;Microsoft Azure;Raspberry Pi;Windows;WordPress                                                                          0.000019
Google Cloud Platform;iOS;Linux;MacOS;Microsoft Azure;WordPress                                                                         0.000019
Android;Google Cloud Platform;IBM Cloud or Watson;WordPress                                                                             0.000019
Docker;Google Cloud Platform;IBM Cloud or Watson;Kubernetes;MacOS                                                                       0.000019
Android;Arduino;AWS;Docker;Heroku;Linux;MacOS;Raspberry Pi;Slack Apps and Integrations                                                  0.000019
Android;Arduino;AWS;Docker;Linux;Microsoft Azure;Windows;WordPress                                                                      0.000019
Name: PlatformWorkedWith, Length: 6287, dtype: float64

In [40]:
df['Country'].value_counts()

United States                         12469
India                                  8403
United Kingdom                         3896
Germany                                3890
Canada                                 2191
France                                 1898
Brazil                                 1818
Netherlands                            1343
Poland                                 1278
Australia                              1208
Spain                                  1161
Italy                                  1117
Russian Federation                     1092
Sweden                                  886
Pakistan                                809
Turkey                                  777
Israel                                  653
Switzerland                             629
Bangladesh                              609
Romania                                 604
Nigeria                                 593
Mexico                                  540
Ukraine                                 539
Austria                                 539
Czech Republic                          500
Indonesia                               499
South Africa                            494
Iran                                    491
Belgium                                 459
Ireland                                 444
                                      ...
Belize                                    4
Tajikistan                                4
Mauritania                                4
Gambia                                    4
Bahamas                                   3
Saint Vincent and the Grenadines          3
Brunei Darussalam                         3
Eritrea                                   3
Papua New Guinea                          2
San Marino                                2
Cape Verde                                2
Timor-Leste                               2
Solomon Islands                           2
Burundi                                   2
Monaco                                    2
Djibouti                                  2
Antigua and Barbuda                       2
Saint Lucia                               1
Gabon                                     1
Liechtenstein                             1
Fiji                                      1
Marshall Islands                          1
Nauru                                     1
Chad                                      1
Grenada                                   1
North Korea                               1
Micronesia, Federated States of...        1
Mali                                      1
Kiribati                                  1
Lesotho                                   1
Name: Country, Length: 183, dtype: int64

In [43]:
filt = df['Country'] == 'United States'

In [45]:
df.loc[filt]['PlatformWorkedWith'].value_counts()

Windows                                                                                                                                       842
Linux;Windows                                                                                                                                 378
Linux                                                                                                                                         358
Microsoft Azure;Windows                                                                                                                       237
Linux;MacOS                                                                                                                                   134
Docker;Linux                                                                                                                                  131
AWS                                                                                                                                           124
AWS;Docker;Linux                                                                                                                              120
MacOS                                                                                                                                         112
Microsoft Azure                                                                                                                               108
AWS;Docker;Linux;MacOS                                                                                                                        103
AWS;Linux                                                                                                                                     102
AWS;Docker                                                                                                                                     96
Docker;Linux;Windows                                                                                                                           94
Linux;MacOS;Windows                                                                                                                            92
Linux;Raspberry Pi;Windows                                                                                                                     92
Android                                                                                                                                        83
MacOS;Windows                                                                                                                                  79
WordPress                                                                                                                                      76
Windows;WordPress                                                                                                                              73
AWS;Windows                                                                                                                                    73
AWS;Linux;MacOS                                                                                                                                72
iOS                                                                                                                                            64
Docker                                                                                                                                         63
AWS;Docker;Kubernetes;Linux;MacOS                                                                                                              63
AWS;Linux;Windows                                                                                                                              61
AWS;Docker;Kubernetes;Linux                                                                                                                    58
Android;Windows                                                                                                                                57
Docker;Linux;MacOS                                                                                                                             54
Android;iOS                                                                                                                                    54
                                                                                                                                             ...
Arduino;AWS;Docker;Google Cloud Platform;Kubernetes;Linux                                                                                       1
AWS;Docker;Linux;MacOS;Raspberry Pi;Windows;WordPress                                                                                           1
Android;AWS;Docker;Google Cloud Platform;IBM Cloud or Watson;iOS;MacOS;Microsoft Azure;Windows                                                  1
Android;Arduino;AWS;Docker;Google Cloud Platform;IBM Cloud or Watson;Kubernetes;Linux;Microsoft Azure;Raspberry Pi;WordPress                    1
Arduino;Google Cloud Platform;MacOS;Raspberry Pi                                                                                                1
Docker;iOS;WordPress                                                                                                                            1
Arduino;Docker;Kubernetes;Linux;MacOS;Microsoft Azure;Raspberry Pi;Slack Apps and Integrations;Windows                                          1
Arduino;Docker;Linux;MacOS;Windows                                                                                                              1
Docker;Google Cloud Platform;Heroku;Microsoft Azure;Slack Apps and Integrations;Windows;WordPress                                               1
AWS;Docker;IBM Cloud or Watson;Linux;MacOS;WordPress                                                                                            1
Android;Arduino;Google Cloud Platform;IBM Cloud or Watson;iOS;Linux;MacOS;Microsoft Azure;Raspberry Pi;Slack Apps and Integrations;Windows      1
AWS;Linux;MacOS;Microsoft Azure                                                                                                                 1
Docker;Google Cloud Platform;Kubernetes;Linux;Slack Apps and Integrations;Windows                                                               1
Android;AWS;Docker;Google Cloud Platform;IBM Cloud or Watson;Linux;Microsoft Azure;Slack Apps and Integrations;Windows                          1
AWS;Docker;Heroku;iOS;Linux                                                                                                                     1
Arduino;Google Cloud Platform;Linux;Microsoft Azure;Windows                                                                                     1
AWS;Docker;Google Cloud Platform;Heroku;iOS;Linux;MacOS;Slack Apps and Integrations;WordPress                                                   1
AWS;Docker;Google Cloud Platform;MacOS;Raspberry Pi                                                                                             1
Android;AWS;Docker;Google Cloud Platform;iOS;Windows                                                                                            1
Android;Linux;Microsoft Azure;Windows;WordPress                                                                                                 1
Google Cloud Platform;Linux;Raspberry Pi;WordPress                                                                                              1
Android;Arduino;Heroku                                                                                                                          1
Android;Arduino;Heroku;Raspberry Pi                                                                                                             1
Android;AWS;Google Cloud Platform;IBM Cloud or Watson;Microsoft Azure;Windows                                                                   1
Android;Arduino;AWS;iOS                                                                                                                         1
Android;iOS;MacOS;Microsoft Azure;Raspberry Pi                                                                                                  1
Android;Docker;Heroku;Linux;MacOS                                                                                                               1
Android;Google Cloud Platform;iOS;Linux;MacOS;Slack Apps and Integrations                                                                       1
Android;Docker;Kubernetes;Raspberry Pi                                                                                                          1
Docker;Heroku;Kubernetes;MacOS;Microsoft Azure;Slack Apps and Integrations;Windows                                                              1
Name: PlatformWorkedWith, Length: 2607, dtype: int64

In [49]:
# Count all platforms worked with in every country
country_grp = df.groupby(['Country'])
country_grp['PlatformWorkedWith'].value_counts()

Country      PlatformWorkedWith
Afghanistan  Android                                                                                                                                                                      7
             Windows                                                                                                                                                                      5
             Android;Windows                                                                                                                                                              4
             Android;Linux;Windows;WordPress                                                                                                                                              3
             Android;Google Cloud Platform;Windows                                                                                                                                        2
             Android;Linux;Windows                                                                                                                                                        2
             Linux;Windows                                                                                                                                                                2
             AWS                                                                                                                                                                          1
             Android;AWS;Google Cloud Platform;Linux;WordPress                                                                                                                            1
             Android;AWS;iOS                                                                                                                                                              1
             Android;Arduino;AWS;Google Cloud Platform;Kubernetes;Linux;Raspberry Pi;Windows;WordPress                                                                                    1
             Android;Arduino;Docker;Linux;Windows;WordPress                                                                                                                               1
             Android;Arduino;Linux;Windows                                                                                                                                                1
             Android;Google Cloud Platform                                                                                                                                                1
             Android;Google Cloud Platform;Linux;Windows;WordPress                                                                                                                        1
             Android;Google Cloud Platform;Microsoft Azure;Windows;WordPress                                                                                                              1
             Android;Linux                                                                                                                                                                1
             Android;iOS;Linux;MacOS                                                                                                                                                      1
             Arduino;AWS;Docker;Google Cloud Platform;Heroku;IBM Cloud or Watson;iOS;Kubernetes;Linux;MacOS;Microsoft Azure;Raspberry Pi;Slack Apps and Integrations;Windows;WordPress    1
             Arduino;Docker;WordPress                                                                                                                                                     1
             Arduino;Linux;Raspberry Pi                                                                                                                                                   1
             Kubernetes                                                                                                                                                                   1
             Linux                                                                                                                                                                        1
Albania      Docker;Linux;Windows                                                                                                                                                         2
             AWS;Docker;Heroku                                                                                                                                                            1
             AWS;Docker;Linux;MacOS                                                                                                                                                       1
             Android;AWS;Docker;Google Cloud Platform;Heroku;Kubernetes;Linux;MacOS;Microsoft Azure;WordPress                                                                             1
             Android;AWS;Microsoft Azure;Windows                                                                                                                                          1
             Android;Arduino;AWS;Google Cloud Platform;Heroku;Linux;Microsoft Azure;Raspberry Pi;Slack Apps and Integrations;Windows;WordPress                                            1
             Android;Arduino;Docker;Linux;Windows;WordPress                                                                                                                               1
                                                                                                                                                                                         ..
Zambia       Android;Docker;iOS;Linux;Microsoft Azure;Windows                                                                                                                             1
             Android;Google Cloud Platform;Linux;Raspberry Pi;Windows;WordPress                                                                                                           1
             Android;Windows                                                                                                                                                              1
             Android;iOS                                                                                                                                                                  1
             Android;iOS;Windows                                                                                                                                                          1
             Linux                                                                                                                                                                        1
Zimbabwe     Android;Windows;WordPress                                                                                                                                                    2
             Windows                                                                                                                                                                      2
             AWS                                                                                                                                                                          1
             AWS;Linux                                                                                                                                                                    1
             AWS;Windows                                                                                                                                                                  1
             Android;AWS;Docker;Kubernetes;Linux;MacOS                                                                                                                                    1
             Android;AWS;Heroku;Kubernetes;Linux;MacOS;WordPress                                                                                                                          1
             Android;AWS;Heroku;iOS;Linux;Windows                                                                                                                                         1
             Android;AWS;iOS;MacOS;Windows;WordPress                                                                                                                                      1
             Android;Arduino;Heroku;Linux;Windows;WordPress                                                                                                                               1
             Android;Docker;Linux;Microsoft Azure;Raspberry Pi                                                                                                                            1
             Android;Google Cloud Platform;MacOS;Windows;WordPress                                                                                                                        1
             Android;Linux;MacOS                                                                                                                                                          1
             Android;Microsoft Azure;Windows                                                                                                                                              1
             Android;Windows                                                                                                                                                              1
             Arduino;Google Cloud Platform;Microsoft Azure;Raspberry Pi;Windows                                                                                                           1
             Arduino;Windows                                                                                                                                                              1
             Docker;Linux;MacOS                                                                                                                                                           1
             Google Cloud Platform;Heroku;Linux;Raspberry Pi;Windows                                                                                                                      1
             Heroku;Linux;Raspberry Pi;WordPress                                                                                                                                          1
             Heroku;Linux;WordPress                                                                                                                                                       1
             Heroku;WordPress                                                                                                                                                             1
             Linux                                                                                                                                                                        1
             Linux;Windows                                                                                                                                                                1
Name: PlatformWorkedWith, Length: 21897, dtype: int64

In [50]:
country_grp['PlatformWorkedWith'].value_counts().loc['India']

PlatformWorkedWith
Windows                                                                  628
Android                                                                  384
Linux;Windows                                                            336
Linux                                                                    301
Android;Windows                                                          123
iOS                                                                      114
Android;Linux;Windows                                                    102
AWS                                                                       86
Android;iOS                                                               86
AWS;Linux                                                                 77
Windows;WordPress                                                         77
WordPress                                                                 76
Linux;Windows;WordPress                                                   74
Microsoft Azure;Windows                                                   73
Android;Linux                                                             59
AWS;Linux;Windows                                                         52
AWS;Docker;Linux                                                          46
Microsoft Azure                                                           46
Docker;Linux                                                              40
MacOS                                                                     38
iOS;MacOS                                                                 38
AWS;Docker;Linux;Windows                                                  36
Docker;Linux;Windows                                                      33
Heroku                                                                    31
Linux;MacOS;Windows                                                       29
AWS;Windows                                                               28
Linux;MacOS                                                               28
Android;WordPress                                                         27
Android;Arduino                                                           26
Docker                                                                    26
                                                                        ...
IBM Cloud or Watson;Linux;MacOS;Windows                                    1
IBM Cloud or Watson;Linux;Microsoft Azure;Slack Apps and Integrations      1
IBM Cloud or Watson;Linux;Windows                                          1
IBM Cloud or Watson;Microsoft Azure;Windows;WordPress                      1
IBM Cloud or Watson;Windows;WordPress                                      1
Kubernetes;Linux;Microsoft Azure                                           1
Kubernetes;Linux;Windows                                                   1
Kubernetes;WordPress                                                       1
Linux;MacOS;Microsoft Azure                                                1
Linux;MacOS;Raspberry Pi                                                   1
Linux;MacOS;Raspberry Pi;Slack Apps and Integrations;WordPress             1
Linux;MacOS;Raspberry Pi;Windows                                           1
Linux;MacOS;Raspberry Pi;Windows;WordPress                                 1
Linux;MacOS;Slack Apps and Integrations;Windows;WordPress                  1
Linux;Microsoft Azure;Raspberry Pi;Windows                                 1
Linux;Microsoft Azure;WordPress                                            1
Linux;Raspberry Pi;Slack Apps and Integrations;Windows;WordPress           1
Linux;Raspberry Pi;WordPress                                               1
MacOS;Slack Apps and Integrations;Windows;WordPress                        1
Microsoft Azure;Slack Apps and Integrations;Windows;WordPress              1
Raspberry Pi;WordPress                                                     1
iOS;Kubernetes;Linux;Windows                                               1
iOS;Linux;MacOS;Microsoft Azure;Windows;WordPress                          1
iOS;Linux;MacOS;WordPress                                                  1
iOS;Linux;Microsoft Azure                                                  1
iOS;MacOS;Raspberry Pi;Windows                                             1
iOS;MacOS;Slack Apps and Integrations                                      1
iOS;MacOS;WordPress                                                        1
iOS;Microsoft Azure                                                        1
iOS;Raspberry Pi                                                           1
Name: PlatformWorkedWith, Length: 1436, dtype: int64

In [51]:
# Median Salary for each country
country_grp['ConvertedComp'].median()

Country
Afghanistan                                   15163.5
Albania                                       15900.0
Algeria                                        9432.0
Andorra                                       88640.0
Angola                                         5292.0
Antigua and Barbuda                               NaN
Argentina                                     17520.0
Armenia                                       21066.0
Australia                                     76831.0
Austria                                       51888.0
Azerbaijan                                    11988.0
Bahamas                                       86706.0
Bahrain                                       40196.0
Bangladesh                                     7068.0
Barbados                                      25074.0
Belarus                                       27600.0
Belgium                                       45396.0
Belize                                        49600.0
Benin                                         45281.5
Bhutan                                        11207.0
Bolivia                                        8676.0
Bosnia and Herzegovina                        21522.0
Botswana                                      16092.0
Brazil                                        17184.0
Brunei Darussalam                              2580.0
Bulgaria                                      29832.0
Burkina Faso                                   3960.0
Burundi                                           NaN
Cambodia                                       8082.0
Cameroon                                       3532.0
                                               ...
Spain                                         38915.0
Sri Lanka                                      8568.0
Sudan                                          2526.0
Swaziland                                      6414.0
Sweden                                        54000.0
Switzerland                                   98599.0
Syrian Arab Republic                           2916.0
Taiwan                                        33142.0
Tajikistan                                        NaN
Thailand                                      23064.0
The former Yugoslav Republic of Macedonia     14136.0
Timor-Leste                                       NaN
Togo                                          11472.0
Trinidad and Tobago                           21936.0
Tunisia                                        7992.0
Turkey                                        17748.0
Turkmenistan                                  50000.0
Uganda                                        11136.0
Ukraine                                       30000.0
United Arab Emirates                          37620.0
United Kingdom                                67215.0
United Republic of Tanzania                   13846.0
United States                                115000.0
Uruguay                                       37824.0
Uzbekistan                                    14760.0
Venezuela, Bolivarian Republic of...           3600.0
Viet Nam                                      10344.0
Yemen                                         36000.0
Zambia                                         5452.0
Zimbabwe                                       7200.0
Name: ConvertedComp, Length: 183, dtype: float64

In [52]:
country_grp['ConvertedComp'].median().loc['India']

10056.0

In [53]:
country_grp['ConvertedComp'].agg(['mean', 'median'])

                                                    mean    median
Country
Afghanistan                                148290.125000   15163.5
Albania                                     25611.000000   15900.0
Algeria                                     10362.812500    9432.0
Andorra                                     88640.000000   88640.0
Angola                                       5292.000000    5292.0
Antigua and Barbuda                                  NaN       NaN
Argentina                                   29010.033473   17520.0
Armenia                                     30421.285714   21066.0
Australia                                  146165.814767   76831.0
Austria                                     83077.661342   51888.0
Azerbaijan                                  14909.142857   11988.0
Bahamas                                     86706.000000   86706.0
Bahrain                                     39592.000000   40196.0
Bangladesh                                  21586.559783    7068.0
Barbados                                    25074.000000   25074.0
Belarus                                     30946.106667   27600.0
Belgium                                     77264.657588   45396.0
Belize                                      49600.000000   49600.0
Benin                                       45281.500000   45281.5
Bhutan                                       8825.600000   11207.0
Bolivia                                     14482.857143    8676.0
Bosnia and Herzegovina                      29012.000000   21522.0
Botswana                                    17403.000000   16092.0
Brazil                                      24941.354365   17184.0
Brunei Darussalam                            2580.000000    2580.0
Bulgaria                                    33284.796610   29832.0
Burkina Faso                                 3960.000000    3960.0
Burundi                                              NaN       NaN
Cambodia                                    37914.875000    8082.0
Cameroon                                     4450.600000    3532.0
...                                                  ...       ...
Spain                                       72619.356110   38915.0
Sri Lanka                                    9651.944954    8568.0
Sudan                                        3795.000000    2526.0
Swaziland                                    6414.000000    6414.0
Sweden                                      66937.709622   54000.0
Switzerland                                142001.936288   98599.0
Syrian Arab Republic                         4833.600000    2916.0
Taiwan                                      52124.560000   33142.0
Tajikistan                                           NaN       NaN
Thailand                                    40902.860000   23064.0
The former Yugoslav Republic of Macedonia   17802.133333   14136.0
Timor-Leste                                          NaN       NaN
Togo                                        11383.200000   11472.0
Trinidad and Tobago                         38127.428571   21936.0
Tunisia                                     12530.166667    7992.0
Turkey                                      26460.987013   17748.0
Turkmenistan                                50000.000000   50000.0
Uganda                                      19151.555556   11136.0
Ukraine                                     35289.943144   30000.0
United Arab Emirates                        43955.622642   37620.0
United Kingdom                             140849.074189   67215.0
United Republic of Tanzania                 26266.400000   13846.0
United States                              208826.496443  115000.0
Uruguay                                     49749.046154   37824.0
Uzbekistan                                 102213.333333   14760.0
Venezuela, Bolivarian Republic of...         6280.611111    3600.0
Viet Nam                                    28342.605769   10344.0
Yemen                                       36000.000000   36000.0
Zambia                                      17506.400000    5452.0
Zimbabwe                                    26338.181818    7200.0

[183 rows x 2 columns]

In [54]:
filt = df['Country'] == 'India'

In [56]:
df.loc[filt]['LanguageWorkedWith'].str.contains('Python').sum()

2670

In [57]:
filt = df['Country'] == 'United States'

In [58]:
us_df = df.loc[filt]

In [59]:
us_df.head()

,MainBranch,Hobbyist,Age,Age1stCode,CompFreq,CompTotal,ConvertedComp,Country,CurrencyDesc,CurrencySymbol,...,SurveyEase,SurveyLength,Trans,UndergradMajor,WebframeDesireNextYear,WebframeWorkedWith,WelcomeChange,WorkWeekHrs,YearsCode,YearsCodePro
Respondent,,,,,,,,,,,,,,,,,,,,,
1157,I am a developer by profession,No,30.0,25,Yearly,84500.0,84500.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"A humanities discipline (such as literature, h...",NaN,Angular.js;Flask;React.js,Just as welcome now as I felt last year,35.0,5,4
3003,I am a developer by profession,Yes,34.0,16,NaN,NaN,NaN,United States,United States dollar,USD,...,Neither easy nor difficult,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,Angular;Angular.js;ASP.NET;ASP.NET Core;React.js,Just as welcome now as I felt last year,45.0,18,10
1791,"I am not primarily a developer, but I write co...",No,43.0,8,NaN,NaN,NaN,United States,NaN,NaN,...,Easy,Appropriate in length,No,NaN,NaN,NaN,NaN,NaN,20,NaN
1436,I am a developer by profession,Yes,53.0,15,Yearly,125000.0,125000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",NaN,NaN,Somewhat more welcome now than last year,5.0,40,30
57952,I am a developer by profession,Yes,45.0,15,Yearly,125000.0,125000.0,United States,United States dollar,USD,...,Easy,Appropriate in length,No,"Computer science, computer engineering, or sof...",ASP.NET Core,ASP.NET;ASP.NET Core,Just as welcome now as I felt last year,45.0,30,23

In [60]:
us_df.to_csv('modified.csv')

In [62]:
us_df.to_csv('modified.tsv', sep='\t')

In [63]:
from sqlalchemy import create_engine
import psycopg2

ModuleNotFoundError: No module named 'psycopg2'